
<ul>
    <li><a href="/">Home Page</a></li>
    <li><a href="/about-us">About Us</a></li>
    <li><a href="/help">Help</a></li>
    <li><a href="/contact-us">Contact Us</a></li>
    <li><a href="/privacy-policy">Privacy Policy</a></li>
    <?php App\Views\get_state(); if (App\Utils\LoginHelper::getInstance()->isLoggedIn()):
        echo '<li><a href="/log-out">Log Out</a></li>';
    else:
        echo '<li><a href="/log-in">Log In</a></li>';
    endif; ?>
</ul>
