
<ul>
    <?php foreach($items as $item): ?>
        <?php if($item[2]): ?>
            <li><b><a href="<?= $item[0]; ?> "><?= $item[1]; ?></a></b></li>
        <?php else: ?>
            <li><a href="<?= $item[0]; ?> "><?= $item[1]; ?></a></li>
        <?php endif; ?>
        
    <?php endforeach; ?>

    <?php App\Views\get_state(); if (App\Utils\LoginHelper::getInstance()->isLoggedIn()):
        echo '<li><a href="/log-out">Log Out</a></li>';
    else:
        echo '<li><a href="/log-in">Log In</a></li>';
    endif; ?>
</ul>
